Repository hanaro5-team-last-pang/hana-hakdang-server, pull requests merged in 2025-01, with the labels that each got.

#9 🔨 develop 브랜치에 PR 시 Unit test하는 github action 스크립트 추가
  .github/workflows/unit-test-on-pr.yml
Labels: :technologist: setting, :white_check_mark: test

#15 ✨ kafka 연결 및 토픽 토픽 서비스 추가
  .github/workflows/unit-test-on-pr.yml
  build.gradle
  src/main/java/com/hanahakdangserver/notification/config/KafkaAdminConfig.java
  src/main/java/com/hanahakdangserver/notification/exception/KafkaTopicCreationFailException.java
  src/main/java/com/hanahakdangserver/notification/exception/KafkaTopicDeletionFailException.java
  src/main/java/com/hanahakdangserver/notification/service/KafkaTopicService.java
  src/main/resources/application.properties
Labels: 🌱 feature

#60 ✨ 강의 시작 + 강의실 입장 API 추가
  src/main/java/com/hanahakdangserver/classroom/controller/ClassroomController.java
  src/main/java/com/hanahakdangserver/classroom/dto/ClassroomEnterResponse.java
  src/main/java/com/hanahakdangserver/classroom/dto/ClassroomStartResponse.java
  src/main/java/com/hanahakdangserver/classroom/enums/ClassroomResponseExceptionEnum.java
  src/main/java/com/hanahakdangserver/classroom/enums/ClassroomResponseSuccessEnum.java
  src/main/java/com/hanahakdangserver/classroom/repository/ClassroomRepository.java
  src/main/java/com/hanahakdangserver/classroom/service/ClassroomService.java
  src/main/java/com/hanahakdangserver/config/RedisConfig.java
  src/main/java/com/hanahakdangserver/config/SecurityConfig.java
  src/main/java/com/hanahakdangserver/lecture/projection/MentorIdOnly.java
  src/main/java/com/hanahakdangserver/lecture/repository/LectureRepository.java
  src/main/java/com/hanahakdangserver/redis/RedisBoundHash.java
  src/main/java/com/hanahakdangserver/redis/RedisBoundSet.java
  src/main/resources/application.properties
  src/test/java/com/hanahakdangserver/lecture/repository/LectureRepositoryTest.java
Labels: 🌱 feature

#97 Task 92 feat refactor review news faq
  src/main/java/com/hanahakdangserver/faq/controller/AnswerController.java
  src/main/java/com/hanahakdangserver/faq/controller/FaqController.java
  src/main/java/com/hanahakdangserver/faq/enums/FaqResponseSuccessEnum.java
  src/main/java/com/hanahakdangserver/news/controller/NewsController.java
  src/main/java/com/hanahakdangserver/news/enums/NewsResponseExceptionEnum.java
  src/main/java/com/hanahakdangserver/news/enums/NewsResponseSuccessEnum.java
  src/main/java/com/hanahakdangserver/news/service/NewsService.java
  src/main/java/com/hanahakdangserver/product/controller/HanaItemController.java
  src/main/java/com/hanahakdangserver/product/enums/HanaItemResponseSuccessEnum.java
  src/main/java/com/hanahakdangserver/product/service/HanaItemService.java
  src/main/java/com/hanahakdangserver/review/controller/ReviewController.java
  src/main/java/com/hanahakdangserver/review/enums/ReviewResponseExceptionEnum.java
  src/main/java/com/hanahakdangserver/review/mapper/ReviewMapper.java
  src/main/java/com/hanahakdangserver/review/projection/ReviewProjection.java
  src/main/java/com/hanahakdangserver/review/repository/ReviewRepository.java
  src/main/java/com/hanahakdangserver/review/service/ReviewService.java
Labels: :bug: fix bug, :recycle: refactor
