Repository hanaro5-team-last-pang/hana-hakdang-server, pull requests merged in 2025-02, with the labels that each got.

#112 :memo: [TASK-106] 유저 정보 조회 업데이트
  src/main/java/com/hanahakdangserver/user/dto/UserInfoResponse.java
  src/main/java/com/hanahakdangserver/user/service/UserService.java
Labels: 💪 update

#118 :fire: [TASK-110] 유저 정보 조회 시 생년월일 추가 제공
  src/main/java/com/hanahakdangserver/user/dto/UserInfoResponse.java
  src/main/java/com/hanahakdangserver/user/service/UserService.java
Labels: 💪 update

#125 🚑 [task-115] access token response body로 전달
  src/main/java/com/hanahakdangserver/auth/controller/AuthController.java
  src/main/java/com/hanahakdangserver/auth/dto/LoginResponse.java
  src/main/java/com/hanahakdangserver/auth/enums/AuthResponseSuccessEnum.java
  src/main/java/com/hanahakdangserver/auth/service/AuthService.java
Labels: :recycle: refactor

#129 :seedling: [TASK-118] 강의 카테고리 목록 반환 api 구현
  src/main/java/com/hanahakdangserver/lecture/controller/LecturesController.java
  src/main/java/com/hanahakdangserver/lecture/dto/LectureCategoriesDetailDTO.java
  src/main/java/com/hanahakdangserver/lecture/dto/LectureCategoriesResponse.java
  src/main/java/com/hanahakdangserver/lecture/enums/LectureResponseSuccessEnum.java
  src/main/java/com/hanahakdangserver/lecture/service/LecturesService.java
Labels: 🌱 feature

#133 ✏️ [task-123] response에 lectureTitle 추가
  src/main/java/com/hanahakdangserver/classroom/dto/ClassroomEnterResponse.java
  src/main/java/com/hanahakdangserver/classroom/dto/ClassroomStartResponse.java
  src/main/java/com/hanahakdangserver/classroom/service/ClassroomService.java
Labels: 💪 update

#142 :zap: [TASK-129] 이메일 링크 수정
  src/main/java/com/hanahakdangserver/email/service/EmailService.java
Labels: :recycle: refactor
